name: CI/CD on GitHub-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      # ❌ Removed npm test since no test script exists

      - name: Build Project
        run: npm run build

      # Optional deploy step
      # - name: Deploy to Firebase / Vercel / SSH / S3 etc.
      #   run: echo "Deploy command here"
